- name: Change permissions for /var/www
  become: true
  file:
    path: "/var/www"
    owner: www-data
    group: www-data
    recurse: yes

- name: Upload deployment zip archive
  become: true
  copy:
    src: "{{ deployment_zip_path }}"
    dest: "/tmp/deployment.zip"
    owner: www-data
    group: www-data
    mode: 0644

- name: Install unzip zip packages
  become: true
  package:
    name: unzip

- name: Unzip deployment zip archive
  become: true
  unarchive:
    src: "/tmp/deployment.zip"
    dest: "/var/www"
    owner: www-data
    group: www-data
    remote_src: yes

- name: Add .env.local configuration
  become: true
  template:
    src: ".env.local.j2"
    dest: "/var/www/.env.local"
    owner: www-data
    group: www-data
    mode: 0644

- name: Change permissions for /var/www
  become: true
  file:
    path: "/var/www"
    owner: www-data
    group: www-data
    recurse: yes

- name: Warmup cache
  become: true
  become_user: www-data
  command: "php /var/www/bin/console cache:warmup --env=prod"

- name: Compile assets
  become: true
  become_user: www-data
  command: "php /var/www/bin/console asset-map:compile"

- name: Run migrations
  become: true
  become_user: www-data
  command: "php /var/www/bin/console --no-interaction doctrine:migrations:migrate"
