- name: Change permissions for /var/www
  become: true
  file:
    path: "/var/www"
    owner: www-data
    group: www-data
    recurse: yes

- name: Upload deployment zip archive
  become: true
  copy:
    src: "{{ deployment_zip_path }}"
    dest: "/tmp/deployment.zip"
    owner: www-data
    group: www-data
    mode: 0644

- name: Unzip deployment zip archive
  become: true
  unarchive:
    src: "/tmp/deployment.zip"
    dest: "/var/www"
    owner: www-data
    group: www-data
    remote_src: yes

- name: Add .env.local configuration
  become: true
  template:
    src: ".env.local.j2"
    dest: "/var/www/.env.local"
    owner: www-data
    group: www-data
    mode: 0644