- name: Install haproxy
  become: true
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Register status of /bluegreen.map
  stat:
    path: /bluegreen.map
  register: bluegreen_map

- name: Configure haproxy bluegreen.cfg
  become: true
  ansible.builtin.template:
    src: ../templates/bluegreen.map.j2
    dest: /bluegreen.map
  when: "not bluegreen_map.stat.exists"

- name: Configure haproxy.cfg
  become: true
  ansible.builtin.template:
    src: ../templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Reload haproxy
  become: true
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
