- hosts: blue_lv_app
  roles:
    - deploy

- hosts: lv_load_balancer
  roles:
    - role: haproxy
      color: blue

- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "Now it's blue"
