- name: Creates secret directory
  become: true
  ansible.builtin.file:
    path: /var/www/secret/
    state: directory
    owner: www-data
    group: www-data

- name: Add cookie file to remote server
  become: true
  become_user: www-data
  ignore_errors: True
  copy:
    src: "{{ cookies }}"
    dest: /var/www/secret/cookies.txt
    owner: www-data
    group: www-data

