- name: Install mariadb server
  become: true
  ansible.builtin.apt:
    name: mariadb-server
    state: present

- name: Make sure pip is present
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Make sure pymysql is present
  become: true
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: Add news user to mariadb server
  become: true
  community.mysql.mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    name: news
    password: '{{ database_news_password }}'
    priv: 'news.*:ALL'
    state: present
    host: '{{ database_news_host }}'

- name: Add markom user to mariadb server
  become: true
  ansible.builtin.mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    name: markom
    password: '{{ database_markom_password }}'
    priv: '*.*:ALL'
    state: present
    host: '{{ database_markom_host }}'

- name: Add markom user to mariadb server
  become: true
  ansible.builtin.mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    name: markom
    password: '{{ database_markom_password }}'
    priv: '*.*:ALL'
    state: present
    host: '{{ database_markom_host_vpn }}'

- name: Change mysql to allow remote connections
  become: true
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    state: present
  notify: Restart mariadb server

- name: Create news database
  become: true
  ansible.builtin.mysql_db:
    login_unix_socket: /run/mysqld/mysqld.sock
    name: news
    state: present

- name: Setup master
  include_tasks: master.yml
  when: master

- name: Setup slave
  include_tasks: slave.yml
  when: slave
