- name: Add 60-as-slave.cnf to mariadb
  become: true
  ansible.builtin.template:
    src: 60-as-slave.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/60-as-slave.cnf
    owner: root
    group: root
  notify: Restart mariadb server

- name: Set master mariadb server
  become: true
  community.mysql.mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: changeprimary
    primary_host: "{{ groups['lv_db'][0] }}"
    primary_user: 'slave'
    primary_password: "{{ database_slave_password }}"

- name: Start server as slave
  become: true
  community.mysql.mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: startslave
