- name: Setup haproxy
  hosts: lv-load-balancer
  tasks:
    - name: Install haproxy
      become: true
      ansible.builtin.apt:
        name: haproxy
        state: present

    - name: Configure haproxy bluegreen.cfg
      become: true
      ansible.builtin.template:
        src: bluegreen.map.j2
        dest: /bluegreen.map

    - name: Configure haproxy.cfg
      become: true
      ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Reload haproxy
      become: true
      ansible.builtin.systemd:
        name: haproxy
        state: reloaded


